### ISSUE TITLE
Suggestion: Provide Conda environment YAML

### ISSUE THREAD

**Issue by mfansler** [fritzbayer/snakemake-with-R#2]
Consider defining the R version and software requirements with a Conda environment YAML. Something like:

**r42.yaml**
```yaml
name: r42
channels:
  - conda-forge
  - nodefaults
dependencies:
  - r-base =4.2
  - r-argparse
```
